indent-width = 4
line-length = 150

[lint]
select = ["ALL", "D212"]
ignore = ["D104", "D203", "D212", "E501", "FBT", "PLR0913", "RET504", "TC006", "ERA001", "RET505", "D213", "D401", "D100", "D101", "ANN204", "TRY300", "T201", "D107", "S101", "N818", "PLR2004", "BLE001", "SIM102"]

[format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"
